### ISSUE TITLE
Add a feature to create dashboards using JSON

### ISSUE THREAD

**Issue by arunselvarajdb** [spaceapegames/terraform-provider-wavefront#47]
Hi,

I would like add a feature which takes JSON file as an input and create a dashboard. This will be really useful in adding existing dashboards from wavefront. Also wavefront has a feature where you can extract the JSON content and create a dashboard out of it. 

**Sample Terraform File**

```
resource "wavefront_dashboard_json" "test_dashboard" {
  dashboard_json = file("${path.module}/test_dashboard.json")
}
```

or 
```
resource "wavefront_dashboard_json" "json_foobar" {
	dashboard_json = <<EOF
{
  "name": "Terraform Test Dashboard",
  "description": "a",
  "eventFilterType": "BYCHART",
  "eventQuery": "",
  "url": "tftestimport",
  "displayDescription": false,
  "displaySectionTableOfContents": true,
  "displayQueryParameters": false,
  "sections": []
...
...
}
EOF
}
```
I have this feature working and I'm in process of adding tests. If you guys are fine with this feature, I will create a PR from my fork when it is ready.

**Comment by louism517** [comment]
Hi @arunselvarajdb,

Yes this sounds like a good idea, it can be fiddly building dashboards using the existing providers and this may provide a lower barrier to entry for those wishing to manage their dashboards as code. 

The first example would be preferable, with `wavefront_dashboard_json` as a separate resource (otherwise we'd have to make every other attribute optional).

Thanks!

**Comment by arunselvarajdb** [comment]
@louism517 Yes it will be separate resource. It was a typo on my end on the second example.

**Comment by arunselvarajdb** [comment]
I created this PR for wavefront_dashboard_json resource - https://github.com/spaceapegames/terraform-provider-wavefront/pull/48

**Comment by arunselvarajdb** [comment]
PR #48 is merged.
